package correlation

import (
	"errors"
	"fmt"
)

const maxIDBytes = 128

// ErrInvalidID is returned when a correlation ID cannot safely cross a
// transport boundary.
var ErrInvalidID = errors.New("invalid correlation ID")

// Validate accepts bounded, log-safe identifiers. UUIDv7 values generated by
// New are a subset of this format, while the wider alphabet lets trusted
// upstream systems retain their own trace identifiers.
func Validate(id string) error {
	if len(id) == 0 {
		return fmt.Errorf("%w: empty", ErrInvalidID)
	}
	if len(id) > maxIDBytes {
		return fmt.Errorf("%w: exceeds %d bytes", ErrInvalidID, maxIDBytes)
	}
	for index := 0; index < len(id); index++ {
		char := id[index]
		if isAllowedIDByte(char) {
			continue
		}
		return fmt.Errorf("%w: unsupported character at byte %d", ErrInvalidID, index)
	}
	return nil
}

func isAllowedIDByte(char byte) bool {
	switch {
	case char >= 'a' && char <= 'z':
		return true
	case char >= 'A' && char <= 'Z':
		return true
	case char >= '0' && char <= '9':
		return true
	}
	switch char {
	case '.', '_', ':', '-':
		return true
	default:
		return false
	}
}
